# check=skip=FromPlatformFlagConstDisallowed
ARG ZONE=edge
FROM --platform=linux/amd64 ghcr.io/bettyblocks/native-wasm-components:${ZONE} AS src

FROM oven/bun:1.3-alpine

# We have a special docker image, because compiling on linux arm64 is not supported by the builder image.
# Apple Silicon can build the wasm components

WORKDIR /app
COPY --from=src /app /app

CMD ["bash"]
