package betty-blocks:init-array@4.0.0;

interface init-array {
    use betty-blocks-types:types/types@3.1.0.{betty-array, betty-schema-model};

    init-array: func(schema-model: option<betty-schema-model>) -> betty-array;
}

world main {
    export init-array;
}
