package betty-blocks:delete@3.0.0;

interface delete {
    use betty-blocks-types:data-api/data-api@3.0.0.{helper-context};
    use betty-blocks-types:types/types@3.0.0.{betty-selected-record};

    delete: func(helper-context: helper-context, %record: betty-selected-record) -> result<string, string>;
}

world main {
    import betty-blocks-types:crud/crud@3.0.0;
    export delete;
}
