package betty-blocks:upsert@2.0.0;

interface upsert {
    use betty-blocks-types:data-api/data-api@2.0.0.{helper-context};
    use betty-blocks-types:types/types@2.0.0.{betty-property-mapping, betty-model, betty-property-path};
    type json-string = string;

    upsert: func(helper-context: helper-context, model: betty-model, mapping: betty-property-mapping, unique-by: list<betty-property-path>, validates: bool) -> result<json-string, string>;
}

world main {
    import betty-blocks-types:crud/crud@2.0.0;
    export upsert;
}
