package betty-blocks:upsert@1.0.0;

interface upsert {
    use betty-blocks-utilities:data-api/data-api.{helper-context};
    use betty-blocks-utilities:crud/crud.{betty-property-mapping, betty-model, betty-property};
    use betty-blocks-utilities:types/types.{betty-property-path};
    type json-string = string;

    record input {
      model: betty-model,
      mapping: betty-property-mapping,
      unique-by: list<betty-property-path>,
      validates: bool
    }

    upsert: func(helper-context: helper-context, input: input) -> result<json-string, string>;
}

world main {
    import betty-blocks-utilities:crud/crud;
    export upsert;
}
