package betty-blocks:parse-json@4.0.0;

interface parse-json {
    use betty-blocks-types:types/types@3.1.0.{betty-schema-model, betty-value};

    parse-json: func(input: string, schema-model: option<betty-schema-model>) -> betty-value;
}

world main {
    export parse-json;
}
