package betty-blocks:logging@0.1.0;

interface logger {
  use wasi:logging/logging@0.1.0-draft.{level};

//  /// A log level, describing a kind of message.
//  enum level {
//    /// Describes messages about the values of variables and the flow of
//    /// control within a program.
//    trace,
//    /// Describes messages likely to be of interest to someone debugging a
//    /// program.
//    debug,
//    /// Describes messages likely to be of interest to someone monitoring a
//    /// program.
//    info,
//    /// Describes messages indicating hazardous situations.
//    warn,
//    /// Describes messages indicating serious errors.
//    error,
//    /// Describes messages indicating fatal errors.
//    critical,
//  }

  type json-string = string;
  record input {
    severity: level,
    variables: json-string,
  }

  log: func(input: input) -> result<_, string>;
}

world main {
  import wasi:logging/logging@0.1.0-draft;
  // import wasi:cli/stdout@0.2.0;

  export logger;
}
