package betty-blocks:expression@0.1.0;

interface expression {
  type json-string = string;

  record output {
    %result: json-string
  }

  record input {
    expression: string,
    variables: json-string,
    schema-model: option<string>,
    debug-logging: option<bool>,
  }

  expression: func(input: input) -> result<output, string>;
}

world main {
  export expression;
}
