package betty-blocks:http@4.0.0;

interface http {
    use betty-blocks-types:types/types@3.1.0.{betty-http-request, betty-http-response};

    http: func(input: betty-http-request) -> result<betty-http-response, string>;
}

world main {
    import wasi:http/outgoing-handler@0.2.6;

    export http;
}
