[package]
name = "http"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
liquid = "0.26.11"
serde_json = "1.0.140"
simd-json = { version = "0.15.1", default-features = false }
tracing = "0.1.41"
url = "2.5.4"
waki = "0.5.1"
wasi = "0.14.2"
wit-bindgen = "0.42.0"
