default: test clean

clean:
	docker container rm -f nats_integration_test
	docker container rm -f wasmcloud_integration_test
	docker container rm -f wadm_integration_test
	docker container rm -f mail_integration_test

test:
	cargo test
