apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: native
  annotations:
    description: betty blocks native app which contains the providers and components to connect to the betty blocks platform
    version: v0.1.0
    experimental.wasmcloud.dev/shared: 'true'
spec:
  components:
    - name: http-wrapper
      # placeholder for the http server to link to (for kubernetes)
      type: component
      properties:
        image: ghcr.io/bettyblocks/http-wrapper:0.1.0
      traits:
        - type: daemonscaler
          properties:
            instances: 1
    - name: crud-component
      type: component
      properties:
        image: ghcr.io/bettyblocks/crud-component:0.1.0
      traits:
        - type: daemonscaler
          properties:
            instances: 1
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.27.0
        config:
        - name: http-config
          properties:
            routing_mode: 'path'
            default_address: '0.0.0.0:8080'
      traits:
        - type: daemonscaler
          properties:
            instances: 10
        - type: link
          properties:
            name: link-native
            target: http-wrapper
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source:
              config:
                - name: path-native
                  properties:
                    address: '0.0.0.0:8080'
                    path: '/admin'
