package betty-blocks:add-variable-to-array@4.0.0;

interface add-variable-to-array {
    use betty-blocks-types:types/types@3.1.0.{betty-array, betty-value};

    add-variable-to-array: func(array: betty-array, item: betty-value) -> result<betty-array, string>;
}

world main {
    export add-variable-to-array;
}
