[package]
name = "logging"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
simd-json = { version = "0.15.1", default-features = false }
tracing = "0.1.41"
wit-bindgen = "0.42.0"
