package betty-blocks:store-file@2.0.0;

interface store {
    use betty-blocks-types:data-api/data-api@2.0.0.{helper-context};
    use betty-blocks-types:types/types@2.0.0.{betty-model, betty-property};

    store-file: func(
        helper-context: helper-context,
	model: betty-model,
	property: list<betty-property>,
	url: string,
	file-extension: option<string>,
    ) -> result<string, string>;
}

world store-file {
    import wasi:http/outgoing-handler@0.2.0;
    import wasi:random/random@0.2.0;
    import betty-blocks-types:data-api/data-api@2.0.0;
    import betty-blocks-types:types/types@2.0.0;
    import betty-blocks-types:upload-file/upload-file@2.0.0;

    export store;
}
