package betty-blocks:store-file@1.0.0;

world store-file {
    import wasi:http/outgoing-handler@0.2.0;
    import wasi:random/random@0.2.0;
    import betty-blocks:data-api/data-api;
    import betty-blocks:types/types;
    import betty-blocks:file/upload-file;

    export betty-blocks:file/store;
}
