package betty-blocks:store-file@1.0.0;

interface store {
    use betty-blocks-utilities:data-api/data-api.{helper-context};
    use betty-blocks-utilities:types/types.{betty-model, betty-property};

    store-file: func(
        helper-context: helper-context,
	model: betty-model,
	property: list<betty-property>,
	url: string,
	file-extension: option<string>,
    ) -> result<string, string>;
}

world store-file {
    import wasi:http/outgoing-handler@0.2.0;
    import wasi:random/random@0.2.0;
    import betty-blocks-utilities:data-api/data-api;
    import betty-blocks-utilities:types/types;
    import betty-blocks-utilities:upload-file/upload-file;

    export store;
}
