name = "send-mail"
version = "1.0.0"
language = "rust"
type = "component"

[component]
wit_world = "email"
wasm_target = "wasm32-wasip2"

[[registry.pull.sources]]
target = "betty-blocks:types"
source = "file://./external/types.wit"

[[registry.pull.sources]]
target = "betty-blocks:smtp/client"
source = "file://./external/smtp.wit"
