package betty-blocks:reassign-variable@3.0.0;

interface reassign-variable {
    use betty-blocks-types:types/types@3.0.0.{json-string, betty-value};

    reassign-variable: func(value: betty-value) -> json-string;
}

world main {
    export reassign-variable;
}
