package betty-blocks:upload-file;

world upload {
    import wasi:http/outgoing-handler@0.2.0;
    import betty-blocks:data-api/data-api-utilities;
    import betty-blocks:types/types;

    export betty-blocks:file/upload-file;
}
