package betty-blocks:ai-agent@1.0.0;

interface ai-agent {
    use betty-blocks-types:types/types@2.4.0.{betty-ai-agent,json-string};

    ai-agent: func(
        ai-agent: betty-ai-agent,
        system-prompt: string,
        prompt: string,
        max-tokens: option<u32>,
    ) -> result<string, string>;
}

world main {
    export ai-agent;
}
