package betty-blocks:http@0.1.0;

interface http {
  enum scheme {
    HTTP,
    HTTPS,
  }

  enum method {
    get,
    head,
    post,
    put,
    delete,
    connect,
    options,
    trace,
    patch,
  }

  type json-string = string;

  record output {
    response-code: u16,
    %as: json-string
  }

  record input {
    method: method,
    protocol: scheme,
    headers: json-string,
    url: string,
    url-parameters: json-string,
    query-parameters: json-string,
    body: string,
    body-parameters: json-string,
  }

  http: func(input: input) -> result<output, string>;
}

world main {
  import wasi:http/outgoing-handler@0.2.6;

  export http;
}
