name = "store-file"
version = "1.0.0"
language = "rust"
type = "component"

[component]
wit_world = "store-file"
wasm_target = "wasm32-wasip2"

[[registry.pull.sources]]
target = "betty-blocks-utilities:types@0.1.0"
source = "file://./external/types.wit"

[[registry.pull.sources]]
target = "betty-blocks-utilities:data-api/data-api"
source = "file://./external/data-api.wit"

[[registry.pull.sources]]
target = "betty-blocks-utilities:upload-file/upload-file"
source = "file://./external/upload-file.wit"
