package betty-blocks:update@2.0.0;

interface update {
    use betty-blocks-types:data-api/data-api@2.0.0.{helper-context};
    use betty-blocks-types:types/types@2.0.0.{betty-property-mapping, betty-model, betty-selected-record, betty-record-json};

    update: func(helper-context: helper-context, mapping: betty-property-mapping, selected-record: betty-selected-record, validates: bool) -> result<betty-record-json, string>;
}

world main {
    import betty-blocks-types:crud/crud@2.0.0;
    export update;
}
