package betty-blocks:update@2.0.0;

interface update {
    use betty-blocks-types:data-api/data-api@2.0.0.{helper-context};
    use betty-blocks-types:types/types@2.0.0.{betty-property-mapping, betty-model};
    type json-string = string;

    record betty-record {
        id: u64
    }

    record selected-record {
        model: betty-model,
        data: option<betty-record>
    }

    record input {
        mapping: betty-property-mapping,
        selected-record: selected-record,
        validates: bool
    }

    update: func(helper-context: helper-context, input: input) -> result<json-string, string>;
}

world main {
    import betty-blocks-types:crud/crud@2.0.0;
    export update;
}
