package betty-blocks:stringify@1.0.0;

interface stringify {
    type json-string = string;

    record output {
        %result: json-string
    }

    stringify: func(input: json-string) -> output;
}

world main {
    export stringify;
}
    