package betty-blocks:stringify@4.0.0;

interface stringify {
    use betty-blocks-types:types/types@3.0.0.{betty-value};

    stringify: func(value: betty-value) -> string;
}

world main {
    export stringify;
}
